Adding base class for actors types
SogasEntertainment/moon-attacks pull request #26
Opened 2023-09-28 21:19 UTC by PauFlorenti

**Issues**
[Default base class #24](https://github.com/SogasEntertainment/moon-attacks/issues/24)

**Summary**
This pr tries to add the super simplified base classes for actors.
These include:
* AActor
* ACharacter
* APawn
* APlayerController
* APlayerState

2023-09-28 21:21 UTC, PauFlorenti commented on project/Plugins/SogasGasSDK/Source/SogasGasSDK/Private/SogasGasSDK/Actors/SGSPlayerController.cpp
> +		PlayerStateVariable->GetAbilitySystemComponent()->InitAbilityActorInfo(PlayerStateVariable, InPawn);
Com comento en el comentari, és necessari, si volem tenir les coses en el `PlayerState`, inicialitzar d'alguna forma el `ActorInfo`. És per això que s'ha de tenir en compte i documentar que si utilitzem el `player state` que proporcionem, cal utilitzar el nostre `PlayerController` o bé inicialitzar el `ActorInfo` en el controller que estigui creant el propi usuari.

2023-09-28 21:24 UTC, PauFlorenti commented on project/Plugins/SogasGasSDK/Source/SogasGasSDK/Public/SogasGasSDK/Actors/SGSActor.h
> +	//~ End IAbilitySystemInterface
Marco el inici i final segons la classe de la que hereta, tal com feien al UMCV, pensant que deixa el codi més organitzat. Però alhora també em dona la sensació de més brut o massa comentari innecessari.
@AlvarAlonso Que et sembla? Organitzem per interfícies o traiem els comentaris i organitzem alfabèticament?

2023-10-02 19:04 UTC, AlvarAlonso requested changes

2023-10-02 19:04 UTC, AlvarAlonso commented on project/Plugins/SogasGasSDK/Source/SogasGasSDK/Public/SogasGasSDK/Actors/SGSPlayerState.h
> +    USGSAbilitySystemComponent* AbilitySystemComponent = nullptr;
Els components haurien de ser UPROPERTY perque els tingui en compte el garbage collector? Necessitem que siguin UPROPERTY per si hi volem editar coses?

2023-10-02 19:04 UTC, AlvarAlonso commented on project/Plugins/SogasGasSDK/Source/SogasGasSDK/Public/SogasGasSDK/Actors/SGSActor.h
> +	//~ End IAbilitySystemInterface
Queda més net si estan separats per interfície crec, ja que les funcionalitats queden més encapsulades i és més fàcil navegar-hi.

2023-10-02 20:07 UTC, PauFlorenti commented on project/Plugins/SogasGasSDK/Source/SogasGasSDK/Public/SogasGasSDK/Actors/SGSPlayerState.h
> +    USGSAbilitySystemComponent* AbilitySystemComponent = nullptr;
Si, segurament si que hagin de ser UPROPERTY(). Bona aquesta.
En quant a editar coses a què et refereixes? Que l'usuari pugui tenir accés a l'`ACS`? Perquè el que s'hauria de fer és a partir del getter, tant en BP com en codi, no?

2023-10-02 21:12 UTC, AlvarAlonso commented on project/Plugins/SogasGasSDK/Source/SogasGasSDK/Public/SogasGasSDK/Actors/SGSActor.h
> +	USGSAbilitySystemComponent* AbilitySystemComponent = nullptr;
Canviar tots els raw pointers que es declarin com a atributs com a TObjectPtr
https://docs.unrealengine.com/5.0/en-US/API/Runtime/CoreUObject/UObject/TObjectPtr/

2023-10-02 21:13 UTC, AlvarAlonso requested changes
He posat comentaris.

2023-10-08 09:44 UTC, AlvarAlonso approved these changes

2023-10-08 09:51 UTC, merged